-- Tabela de Usuários da Chácara
CREATE TABLE IF NOT EXISTS chacara_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL, -- Referência ao usuário do sistema (dono da chácara)
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  last_reading NUMERIC DEFAULT 0,
  last_water_reading NUMERIC DEFAULT 0,
  has_energy BOOLEAN DEFAULT TRUE,
  has_water BOOLEAN DEFAULT TRUE,
  energy_active BOOLEAN DEFAULT TRUE,
  water_active BOOLEAN DEFAULT TRUE,
  energy_meters_count INTEGER DEFAULT 1,
  water_meters_count INTEGER DEFAULT 1,
  last_reading_2 NUMERIC DEFAULT 0,
  last_water_reading_2 NUMERIC DEFAULT 0,
  energy_readings JSONB DEFAULT '[]',
  water_readings JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Contas de Energia da Chácara
CREATE TABLE IF NOT EXISTS chacara_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL, -- Referência ao usuário do sistema
  chacara_user_id BIGINT REFERENCES chacara_users(id) ON DELETE CASCADE,
  month_reference TEXT NOT NULL,
  reading_date DATE NOT NULL,
  due_date DATE NOT NULL,
  prev_reading NUMERIC NOT NULL,
  curr_reading NUMERIC NOT NULL,
  prev_reading_2 NUMERIC DEFAULT 0,
  curr_reading_2 NUMERIC DEFAULT 0,
  kwh_value NUMERIC NOT NULL,
  water_prev_reading NUMERIC DEFAULT 0,
  water_curr_reading NUMERIC DEFAULT 0,
  water_prev_reading_2 NUMERIC DEFAULT 0,
  water_curr_reading_2 NUMERIC DEFAULT 0,
  water_value NUMERIC DEFAULT 0,
  water_service_fee NUMERIC DEFAULT 0,
  apportionment_value NUMERIC DEFAULT 0,
  include_apportionment BOOLEAN DEFAULT TRUE,
  reserve_fund NUMERIC DEFAULT 0,
  total NUMERIC NOT NULL,
  include_reserve_fund BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'pending',
  amount_paid NUMERIC DEFAULT 0,
  payment_observation TEXT,
  energy_readings JSONB DEFAULT '[]',
  water_readings JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Adicionar colunas caso as tabelas já existam
DO $$
BEGIN
    BEGIN
        ALTER TABLE chacara_users ADD COLUMN energy_active BOOLEAN DEFAULT true;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_users ADD COLUMN water_active BOOLEAN DEFAULT true;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_users ADD COLUMN energy_meters_count INTEGER DEFAULT 1;
    EXCEPTION WHEN duplicate_column THEN END;
    
    BEGIN
        ALTER TABLE chacara_users ADD COLUMN water_meters_count INTEGER DEFAULT 1;
    EXCEPTION WHEN duplicate_column THEN END;
    
    BEGIN
        ALTER TABLE chacara_users ADD COLUMN last_reading_2 NUMERIC DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN END;
    
    BEGIN
        ALTER TABLE chacara_users ADD COLUMN last_water_reading_2 NUMERIC DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_bills ADD COLUMN prev_reading_2 NUMERIC DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN END;
    
    BEGIN
        ALTER TABLE chacara_bills ADD COLUMN curr_reading_2 NUMERIC DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN END;
    
    BEGIN
        ALTER TABLE chacara_bills ADD COLUMN water_prev_reading_2 NUMERIC DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN END;
    
    BEGIN
        ALTER TABLE chacara_bills ADD COLUMN water_curr_reading_2 NUMERIC DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_users ADD COLUMN energy_readings JSONB DEFAULT '[]';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_users ADD COLUMN water_readings JSONB DEFAULT '[]';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_bills ADD COLUMN energy_readings JSONB DEFAULT '[]';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_bills ADD COLUMN water_readings JSONB DEFAULT '[]';
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_bills ADD COLUMN amount_paid NUMERIC DEFAULT 0;
    EXCEPTION WHEN duplicate_column THEN END;

    BEGIN
        ALTER TABLE chacara_bills ADD COLUMN payment_observation TEXT;
    EXCEPTION WHEN duplicate_column THEN END;
END $$;

-- Tabela de Configurações da Chácara
CREATE TABLE IF NOT EXISTS chacara_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE, -- Referência ao usuário do sistema
  default_kwh NUMERIC DEFAULT 0.95,
  default_due_day INTEGER DEFAULT 10,
  default_reading_day INTEGER DEFAULT 5,
  reserve_fund_value NUMERIC DEFAULT 50.00,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (opcional, mas recomendado se não usar service role)
ALTER TABLE chacara_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE chacara_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE chacara_settings ENABLE ROW LEVEL SECURITY;

-- Políticas básicas (se não usar service role)
-- CREATE POLICY "Users can manage their own chacara users" ON chacara_users FOR ALL USING (auth.uid() = user_id);
-- CREATE POLICY "Users can manage their own chacara bills" ON chacara_bills FOR ALL USING (auth.uid() = user_id);
-- CREATE POLICY "Users can manage their own chacara settings" ON chacara_settings FOR ALL USING (auth.uid() = user_id);
