CREATE TABLE IF NOT EXISTS personal_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid(),
  title TEXT NOT NULL,
  description TEXT,
  due_date DATE,
  priority TEXT CHECK (priority IN ('low', 'medium', 'high')) DEFAULT 'medium',
  status TEXT CHECK (status IN ('pending', 'completed')) DEFAULT 'pending',
  eisenhower_quadrant TEXT CHECK (eisenhower_quadrant IN ('urgent_important', 'not_urgent_important', 'urgent_not_important', 'not_urgent_not_important')) DEFAULT 'not_urgent_not_important',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE personal_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own personal tasks"
  ON personal_tasks
  FOR ALL
  USING (auth.uid() = user_id);
