-- Create Financial Categories Table
CREATE TABLE IF NOT EXISTS financial_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('receita', 'despesa')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Financial Accounts Table
CREATE TABLE IF NOT EXISTS financial_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  name TEXT NOT NULL,
  initial_balance NUMERIC(10, 2) DEFAULT 0,
  type TEXT NOT NULL CHECK (type IN ('corrente', 'credito', 'dinheiro')),
  due_day INTEGER,
  closing_day INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Financial Transactions Table
CREATE TABLE IF NOT EXISTS financial_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  description TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('receita', 'despesa')),
  category_id BIGINT REFERENCES financial_categories(id) ON DELETE SET NULL,
  account_id BIGINT REFERENCES financial_accounts(id) ON DELETE SET NULL,
  date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pago', 'pendente')),
  is_installment BOOLEAN DEFAULT FALSE,
  installment_number INTEGER,
  total_installments INTEGER,
  parent_transaction_id BIGINT REFERENCES financial_transactions(id) ON DELETE CASCADE,
  splits JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Financial Responsibles Table
CREATE TABLE IF NOT EXISTS financial_responsibles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_financial_categories_user_id ON financial_categories(user_id);
CREATE INDEX IF NOT EXISTS idx_financial_accounts_user_id ON financial_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_financial_transactions_user_id ON financial_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_financial_transactions_date ON financial_transactions(date);
CREATE INDEX IF NOT EXISTS idx_financial_responsibles_user_id ON financial_responsibles(user_id);

-- Habilitar RLS
ALTER TABLE financial_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_responsibles ENABLE ROW LEVEL SECURITY;

-- Políticas de Segurança
CREATE POLICY "Users can manage their own financial categories" ON financial_categories FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own financial accounts" ON financial_accounts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own financial transactions" ON financial_transactions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own financial responsibles" ON financial_responsibles FOR ALL USING (auth.uid() = user_id);
