-- Create Safety Reports Table
CREATE TABLE IF NOT EXISTS safety_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  report_number TEXT NOT NULL,
  location TEXT NOT NULL,
  supervisor TEXT,
  status TEXT DEFAULT 'pending',
  completed_at TIMESTAMP WITH TIME ZONE,
  logo_1 TEXT, -- Base64 or URL
  logo_2 TEXT, -- Base64 or URL
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Ensure all columns exist if table was previously created with fewer columns
ALTER TABLE safety_reports ADD COLUMN IF NOT EXISTS supervisor TEXT;
ALTER TABLE safety_reports ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE safety_reports ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE safety_reports ADD COLUMN IF NOT EXISTS logo_1 TEXT;
ALTER TABLE safety_reports ADD COLUMN IF NOT EXISTS logo_2 TEXT;

-- Create Safety Non Conformities Table
CREATE TABLE IF NOT EXISTS safety_non_conformities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT REFERENCES safety_reports(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  suggestion TEXT NOT NULL,
  normative_items TEXT NOT NULL,
  classification TEXT NOT NULL,
  due_date DATE,
  image_data TEXT,
  images JSONB DEFAULT '[]'::jsonb, -- Store array of base64 or URLs
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE safety_non_conformities ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb;
ALTER TABLE safety_non_conformities ADD COLUMN IF NOT EXISTS image_data TEXT;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_safety_reports_user_id ON safety_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_safety_non_conformities_report_id ON safety_non_conformities(report_id);

-- Habilitar RLS
ALTER TABLE safety_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE safety_non_conformities ENABLE ROW LEVEL SECURITY;

-- Políticas de Segurança
DROP POLICY IF EXISTS "Users can manage their own safety reports" ON safety_reports;
CREATE POLICY "Users can manage their own safety reports" ON safety_reports FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can manage their own safety non conformities" ON safety_non_conformities;
CREATE POLICY "Users can manage their own safety non conformities" ON safety_non_conformities FOR ALL USING (
  EXISTS (SELECT 1 FROM safety_reports WHERE id = safety_non_conformities.report_id AND user_id = auth.uid())
);

