-- Create Marketing Clients Table
CREATE TABLE IF NOT EXISTS marketing_clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  name TEXT NOT NULL,
  company TEXT,
  phone TEXT,
  plan_name TEXT,
  plan_value NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'prospect', 'inativo')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Marketing Payments Table
CREATE TABLE IF NOT EXISTS marketing_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  client_id BIGINT REFERENCES marketing_clients(id) ON DELETE CASCADE,
  month_reference TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  due_date DATE NOT NULL,
  payment_date DATE,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'pago', 'atrasado')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Marketing Posts (Scheduling & Calendar) Table
CREATE TABLE IF NOT EXISTS marketing_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  title TEXT NOT NULL,
  scheduled_date DATE NOT NULL,
  scheduled_time TEXT,
  social_network TEXT NOT NULL CHECK (social_network IN ('instagram', 'facebook', 'youtube', 'tiktok', 'other')),
  status TEXT NOT NULL DEFAULT 'rascunho' CHECK (status IN ('rascunho', 'programado', 'feito', 'aprovado', 'publicado')),
  caption TEXT,
  attachment_url TEXT,
  client_id BIGINT REFERENCES marketing_clients(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_marketing_clients_user_id ON marketing_clients(user_id);
CREATE INDEX IF NOT EXISTS idx_marketing_payments_user_id ON marketing_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_marketing_payments_due_date ON marketing_payments(due_date);
CREATE INDEX IF NOT EXISTS idx_marketing_posts_user_id ON marketing_posts(user_id);
CREATE INDEX IF NOT EXISTS idx_marketing_posts_scheduled_date ON marketing_posts(scheduled_date);

-- Enable RLS (Row Level Security)
ALTER TABLE marketing_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketing_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketing_posts ENABLE ROW LEVEL SECURITY;

-- Safety Policies
CREATE POLICY "Users can manage their own marketing clients" ON marketing_clients FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own marketing payments" ON marketing_payments FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own marketing posts" ON marketing_posts FOR ALL USING (auth.uid() = user_id);

-- Migration query in case the table already exists and needs the updated status check constraint:
-- ALTER TABLE marketing_posts DROP CONSTRAINT IF EXISTS marketing_posts_status_check;
-- ALTER TABLE marketing_posts ADD CONSTRAINT marketing_posts_status_check CHECK (status IN ('rascunho', 'programado', 'feito', 'aprovado', 'publicado'));

