-- Create Clients Table
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Client Sales Table
CREATE TABLE IF NOT EXISTS client_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  total_amount NUMERIC(10, 2) NOT NULL,
  installment_count INTEGER NOT NULL,
  purchase_date DATE NOT NULL,
  due_day INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create Client Installments Table
CREATE TABLE IF NOT EXISTS client_installments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  sale_id BIGINT REFERENCES client_sales(id) ON DELETE CASCADE,
  installment_number INTEGER NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  due_date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pendente', 'pago')) DEFAULT 'pendente',
  payment_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_clients_user_id ON clients(user_id);
CREATE INDEX IF NOT EXISTS idx_client_sales_user_id ON client_sales(user_id);
CREATE INDEX IF NOT EXISTS idx_client_installments_user_id ON client_installments(user_id);
CREATE INDEX IF NOT EXISTS idx_client_installments_due_date ON client_installments(due_date);

-- Habilitar RLS
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_installments ENABLE ROW LEVEL SECURITY;

-- Políticas de Segurança
CREATE POLICY "Users can manage their own clients" ON clients FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own client sales" ON client_sales FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own client installments" ON client_installments FOR ALL USING (auth.uid() = user_id);
